### DISCUSSION TITLE
Login Controller - clarifying loginHandler usage

### DISCUSSION THREAD

**Discussion by alexanderankin** [micronaut-projects/micronaut-security#1181] [General]
Hi all,

<details><summary>my application.yaml for context </summary>

```yaml
micronaut:
  application:
    name: my-application
  security:
    authentication: session
    redirect:
      unauthorized.url: /login # default is / and we want to let users log in
      prior-to-login: true # redirect user back to page they wanted

    # simply using defaults here:
    #endpoints:
    #  login:
    #    enabled: true
    #    path: /login

  server:
    port: 8080

  router:
    static-resources:
      default:
        paths:
          - classpath:/public
```

</details>

I am trying to implement the [same functionality as spring's formLogin configuration](https://stackoverflow.com/questions/74830560/does-micronaut-have-a-built-in-login-form-like-spring-boot-does) and i notice that there is some special [handling](https://github.com/spring-projects/spring-security/blob/7f6e0242e58840bbb1de323a6455f94e809d7055/web/src/main/java/org/springframework/security/web/authentication/ui/DefaultLoginPageGeneratingFilter.java#L191-L197) to pull the auth failure out of the session.

For Micronaut's case, it doesn't save the [outcome into the session](https://github.com/micronaut-projects/micronaut-security/blob/4fd4ff6231b29b949c66a333d4b6babf91aca8be/security/src/main/java/io/micronaut/security/endpoints/LoginController.java#L91-L99) and, lets say that is a job for the login handler - well, it isn't called in the event of no authenticator response. This potentially leaks the case of no AuthenticationProvider configured to the user (never the case in spring, it auto-generates a username/password and prints it out on startup - based on `spring.security.user.{name,password}`).

I think my best bet is to `@Replaces` the SessionLoginHandler and, before calling super, set an attribute on the request with the AuthenticationResponse's message, with a fallback to "authentication failed (no additional information)". Not sure if i am missing a better way to do it.
