### DISCUSSION TITLE
What is the correct ldap context properties syntax

### DISCUSSION THREAD

**Discussion by dncahyo** [micronaut-projects/micronaut-security#1353] [Q&A]
Hello,
I've been getting error PartialResultException
and it seem the solution is to set ```Context.REFERRAL``` to ```follow``` ([according to SO answer here](https://stackoverflow.com/questions/5505351/jndi-with-active-directory-partialresultexception))
I've tried several formats to set it:
![image](https://github.com/micronaut-projects/micronaut-security/assets/9062641/98fcdc0a-b703-4517-9a50-340b6f3feb3a)

but the error still persists:
![image](https://github.com/micronaut-projects/micronaut-security/assets/9062641/46e2d213-62f7-4316-9cc9-e965ec1da3cf)
Akhq is using micronaut 3.7.3
![image](https://github.com/micronaut-projects/micronaut-security/assets/9062641/d1dc5a08-9dac-4ad8-ac43-34ead8753389)

I would like to know what is the correct settings to be used in application.yml config 🙏

Thanks a lot!

**Comment by djeanprost** [comment]
Answer is this one, I tested it.
```
micronaut:
  security:
    ldap:
      default:
        enabled: true
        context:
          server: "ldap://myserver:389"
          managerDn: "CN=myaccount,OU=Comptes Service,DC=HereIAm,DC=LOCAL"
          managerPassword: "password"
          properties:
            - java.naming.referral: "follow"
```
