### DISCUSSION TITLE
Hot to authenticate after signup? HELP, please

### DISCUSSION THREAD

**Discussion by ArthurHarkivsky** [micronaut-projects/micronaut-security#1518] [Q&A]
Hot to authenticate after signup?

```
    @Transactional
    public AuthenticationResponse signup(RegisterRequest registerRequest, HttpRequest<?> httpRequest) {
        var user = User.builder()
                .firstName(registerRequest.getFirstname())
                .lastName(registerRequest.getLastname())
                .email(registerRequest.getEmail())
                .username(Optional.ofNullable(registerRequest.getPhone()).orElse(registerRequest.getEmail()))
                .password(cryptographicService.encode(registerRequest.getPassword()))
                .build();
        var savedUser = userService.save(user);
        var jwtToken = jwtService.generateToken(user);
        var refreshToken = jwtService.generateRefreshToken(user);
        saveUserToken(savedUser, jwtToken);
//        authenticationProvider.authenticate(httpRequest, new UsernamePasswordCredentials(user.getUsername(), user.getPassword()));

        return AuthenticationResponse.builder()
                .accessToken(jwtToken)
                .refreshToken(refreshToken)
                .build();
    }
```
For logout I am sending Atuhorization header with "Bearer accessTokenValueABC", but AuthenticationProvider **is not being called.**

Conf
```
micronaut:
  server:
    port: 5050
  application:
    name: api
  security:
    authentication: bearer
    endpoints:
      login:
        enabled: true
    redirect:
      login-success: /home
      login-failure: /login/failed
    intercept-url-map:
      - pattern: /v1/**
        http-method: POST
        access:
          - isAnonymous()
          - isAuthenticated()
    token:
      jwt:
        enabled: true
        signatures:
          generator:
            secret: ffffffffff
        expiration: 86400000
      refresh-token:
        expiration: 86400000
```
