### DISCUSSION TITLE
AWS ALB authentication and micronaut user details

### DISCUSSION THREAD

**Discussion by rferreira** [micronaut-projects/micronaut-security#579] [Q&A] [answered]
Hello folks, I'm trying to integrate Micronaut with [AWS' ALB authentication](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html) and I've gotten the access token to work well by simply setting the correct header like this: 

```
security:
    token:
      jwt:
        enabled: true
        bearer:
          header-name: "X-Amzn-Oidc-Accesstoken"
          enabled: true
          prefix: ""
        signatures:
          jwks:
            cognito:
              url: "https://cognito-idp.us-east-1.amazonaws.com/*******/.well-known/jwks.json"

````

But, according to the AWS documentation, claims are coming from a separate header ```x-amzn-oidc-data``` and I could user some pointers on how to wire that into the JWT claim flow to hydrate the UserDetails with the correct information. Has anyone successfully integrated Micronaut behind AWS ALB's user authentication logic? 

Big thanks
