### DISCUSSION TITLE
It should probably be possible to handle resource owner password grant the same way as client credentials

### DISCUSSION THREAD

**Discussion by pfyod** [micronaut-projects/micronaut-security#585] [Ideas]
Out use-case is that we need to call external API that only supports the `password` grant. Credentials are not provided by the user (like in the flow described [here](https://micronaut-projects.github.io/micronaut-security/latest/guide/#password)), but are configured within the application. 

Could look something like this in the configuration:

```
micronaut:
  security:
    oauth2:
      clients:
        companyauthserver: # ← this third-party OAuth server only supports the "password" grant
          client-id: 'XXX'
          client-scret: 'YYY'
          password: # ← instead of "client-credentials"
            service-id-regex: 'inventory'
            username: foo # configured username
            password: bar # configured password
          token:
            url: "https://foo.bar/token"
            auth-method': "client_secret_basic"
```

This is kind-of not how OAuth 2 resource owner password grant is _meant_ to be used, but probably not that uncommon (calling OAuth secured APIs with special "system" users). 

Actual implementation would be basically the same as the one that currently exists for the client credentials grant.
