### ISSUE TITLE
Oauth 2.0 password authentication does not work with openId configuration

### ISSUE THREAD

**Issue by uulyar** [micronaut-projects/micronaut-security#1071]
### Expected Behavior

1. `OpenIdPasswordAuthenticationProvider` created by `PasswordGrantFactory` with this configuration.

```
oauth2:
      clients:
        internal:
          grant-type: password
          client-id: xxx
          client-secret: xxx
          openid:
            issuer: xxx
```

### Actual Behaviour

1.  `OpenIdPasswordAuthenticationProvider` does not created because `PasswordGrantCondition` has a bag with finding beans by qualifier:

```
boolean hasOpenIdProviderMetadata =
 beanContext.containsBean(OpenIdProviderMetadata.class, Qualifiers.byName(failureMsgPrefix));
````

 `failureMsgPrefix` should be replaced with `clientConfiguration.getName()`

2. `OpenIdPasswordAuthenticationProvider` does not created because has breaking verification in constructor:

```
        Optional<TokenEndpointConfiguration> tokenEndpointConfiguration = clientConfiguration.getOpenid().flatMap(OpenIdClientConfiguration::getToken);
        if (!tokenEndpointConfiguration.isPresent()) {
            throw new IllegalArgumentException("Missing token endpoint configuration");
        }
```

### Environment Information

- JDK 17

### Version

3.5.0
