### ISSUE TITLE
Crash when setting openid provider for Keycloak 8.0.0

### ISSUE THREAD

**Issue by TheoMuffin** [micronaut-projects/micronaut-security#110]
When setting openid issuer to that of Keycloak 8.0.0 then Micronaut crashes with ```Error instantiating bean of type [io.micronaut.security.oauth2.client.DefaultOpenIdClient]: No enum constant io.micronaut.security.oauth2.endpoint.AuthenticationMethod.TLS_CLIENT_AUTH```. The behavior doesn't change with different versions of Micronaut/security/oauth libraries, including snapshot versions. The problem goes away when using Keycloak 7.0.1 or older.

Steps to reproduce:

- Make a new bat file in Keycloak 8.0.0 > bin repository in order to start it up on a different port than micronaut: ```./standalone.bat -Djboss.socket.binding.port-offset=100```
- Configuring the first administration account at http://localhost:8180/auth/ may or may not be needed.
- Set the following in Micronauts application.yml: 
```
 security:
    enabled: true
    oauth2:
      enabled: true
      clients:
        fileserver:
          openid:
            issuer: 'http://localhost:8180/auth/realms/master'
    token:
      jwt:
        enabled: true
```
- Run micronaut
