### ISSUE TITLE
Support loading JWKS by file

### ISSUE THREAD

**Issue by zephyrok** [micronaut-projects/micronaut-security#1109]
### Feature description

We had a requirement where we needed to load the JWKS through a json file because the keys were to exposed as a remote endpoint for security reasons. Currently the framework only support loading JWKS through a remote url.

I got around this by extending the `JwksSignature` class and overriding the `loadJwkSet` method to use the overloaded `JWKSet.load` method that accepts a `File` object.

```java
try {
    return JWKSet.load(Paths.get(file).toFile());
} catch (IOException | ParseException e) {
```

This could be supported natively by the framework, we could have an additional property called "path" to provide either an external file or a file in the classpath, for example:

```yaml
micronaut:
  security:
    token:
      jwt:
        signatures:
          jwks:
            verifier:
              path: file:/path/to/jwks.json
```
I'd love to work on a PR if this feature is worth adding.
