### ISSUE TITLE
Duplicate Client credentials header token handler

### ISSUE THREAD

**Issue by mplanchant** [micronaut-projects/micronaut-security#1148]
### Expected Behavior

I'm trying to make use of the Http Client Filter for Client Credentials (https://micronaut-projects.github.io/micronaut-security/latest/guide/#clientecredentialshttpclient)

I have the following config in my properties file:

```
micronaut:
  application:
    name: my-app
  http:
    services:
      dev:
        urls:
          - https://dev.com
  security:
    filter:
      enabled: false
    oauth2:
      clients:
        auth:
          grant-type: client_credentials
          client-id: 'client-id'
          client-secret: 'client-secret'
          client-credentials:
            service-id-regex: 'dev'
            scope: 'my-scope'
          token:
            url: 'https://auth.com/oauth2/token'
            auth-method: client_secret_post
```
I'm expecting the Authorization HTTP header to be added to requests using the `dev` HTTP Client.

### Actual Behaviour

I'm seeing the following in the logs:

```
Bean [Definition: io.micronaut.security.oauth2.client.clientcredentials.propagation.ClientCredentialsHeaderTokenPropagator] will not be loaded due to failing conditions:
 * Client credentials header token handler disabled due to a lack of configuration
 * Custom condition [class io.micronaut.security.oauth2.client.clientcredentials.propagation.ClientCredentialsHeaderPropagatorEnabled] failed evaluation         
 ```

If I modify my config to:

```
micronaut:
  application:
    name: my-app
  http:
    services:
      dev:
        urls:
          - https://dev.com
  security:
    filter:
      enabled: false
    oauth2:
      clients:
        auth:
          grant-type: client_credentials
          client-id: 'client-id'
          client-secret: 'client-secret'
          client-credentials:
            service-id-regex: 'dev'
            scope: 'my-scope'
            header-propagation:
              enabled: true
              prefix: 'Bearer'
              header-name: 'Authorization'
          token:
            url: 'https://auth.com/oauth2/token'
            auth-method: client_secret_post
```

I see the following in the logs:

```
Internal Server Error: Failed to inject value for parameter [defaultTokenPropagator] of class: io.micronaut.security.oauth2.client.clientcredentials.propagation.ClientCredentialsHttpClientFilter\n\nMessage: Multiple possible bean candidates found: [io.micronaut.security.oauth2.client.clientcredentials.propagation.ClientCredentialsHeaderTokenPropagator, io.micronaut.security.oauth2.client.clientcredentials.propagation.DefaultClientCredentialsTokenPropagator]"
```

### Environment Information

```
io.micronaut.security:micronaut-security-oauth2:3.8.3
io.micronaut.security:micronaut-security-jwt:3.8.3
```

### Version

3.7.3
