### ISSUE TITLE
Feature Request: Support Client Credentials Grant

### ISSUE THREAD

**Issue by TeNNoX** [micronaut-projects/micronaut-security#12]
I see a lot of documentation, but none detailing how to authenticate via OAuth2 in HTTP client.
Is this planned in this library?

Or is it already implement and I just didn't find it?
Or is it already supported by existing micronaut library?

**Comment by rafaelrenanpacheco** [comment]
On Spring we use client credentials for communication between microservices, we don't propagate the user's access token because the user's access token expires very often and the backend don't have the user's refresh token to request a new access token. Client credentials access token can have a longer expiration time, which results in few refresh requests between microservices. Also, when the client credentials access token expires, Spring will automatically request a new client credential access token and retry the request.

So far we can't use Micronaut Security due this missing feature.

**Comment by danielegts** [comment]
I have a third party software that needs to call an api which I implemented using Micronaut: I would like to use Okta as an Identity manager. 

If client_credentials grant is still not available, how can I make the third party software authenticate against the services I exposed using Micronaut?

A partial answer came from this tutorial:
https://piotrminkowski.wordpress.com/2019/04/25/micronaut-tutorial-security/
but I wasn't able to figure how to modify the configuration they propose to get user credentials from Okta instead of specifying them in the application.yml itself.

On the other hand Micronaut Okta tutorial (https://guides.micronaut.io/micronaut-oauth2-okta/guide/index.html) uses authorization code grant, so it looks like a browser is required to complete the authentication:
https://stackoverflow.com/questions/48821666/is-it-possible-to-get-authorization-code-in-oauth-2-0-without-web-browser-in-jav
so I can't use this authentication flow in my case.

Maybe you can put me on the right track...

**Comment by jaecktec** [comment]
I know this is closed, but it's the first result on common search engines, therefore I'm linking to the docs:
https://micronaut-projects.github.io/micronaut-security/latest/guide/#clientcredentials

**Comment by pfyod** [comment]
@sdelamo: any plans to also support the `password` grant? We have an API that we'd like to talk to using Micronaut's declarative HTTP client, but it requires us to use the `password` grant (with a special "system" username/password). Would be great if it was possible to do that using just configuration.

**Comment by sdelamo** [comment]
@pfyod we support password grant already https://micronaut-projects.github.io/micronaut-security/latest/guide/#password ?

**Comment by pfyod** [comment]
@sdelamo: Unless I'm missing something, https://micronaut-projects.github.io/micronaut-security/latest/guide/#password is about forwarding user provided credentials to a third party OAuth2 provider. I our use-case, we need to get tokens with _configured_ credentials. Something like this:
```
micronaut:
  security:
    oauth2:
      clients:
        companyauthserver: # ← this third-party OAuth server only supports the "password" grant
          client-id: 'XXX'
          client-scret: 'YYY'
          password: # ← instead of "client-credentials"
            service-id-regex: 'inventory'
            username: foo # configured username
            password: bar # configured password
          token:
            url: "https://foo.bar/token"
            auth-method': "client_secret_basic",
```

Obviously, we can implement it, but the only differences to the current built-in "client credentials" handling would be sending different grant type (`password` instead of `client_credentials`) and username/password to the token endpoint.

**Comment by jaecktec** [comment]
Don't want to be the annoying person, but this issue is about client_credentials. 🙈

**Comment by pfyod** [comment]
> Don't want to be the annoying person, but this issue is about client_credentials. 🙈

Sorry if it was not appropriate for me to ask questions here, but supporting getting tokens with the `password` grant in a manner that I described above is essentially the same code as the one that currently handles `client_credentials`. 

Also, the issue was renamed from "Question: Is this going to implement OAuth2 client?" to "Feature Request: Support Client Credentials Grant" and there was a discussion up top whether it's the `password` grant that needs to be supported. 

Since it's kinda of an edge case scenario, I did not want to open a new issue.

**Comment by sdelamo** [comment]
@pfyod can we move this to [Discussions](https://github.com/micronaut-projects/micronaut-security/discussions)?

**Comment by pfyod** [comment]
@sdelamo https://github.com/micronaut-projects/micronaut-security/discussions/585

**Comment by IgorEulalio** [comment]
I have a case in my company.

We have client credentials per department and need to authorize in a external system to generate a JWT and send to a gateway, that will validate this token.

I try this code:
```yml
 security:
    oauth2:
          clients:
            companyauthserver:
              client-id: '{my_client_id'
              client-secret: '{my_client_secret}'
              client-credentials:
                service-id-regex: 'cvm_client'
              token:
                url: "https://${dns_of_my_authorizator}/api/oauth/token"
                auth-method: client_secret_basic`
```
My client is configured:

```java
@Client(id = "cvm_client")
public interface CvmClient {

    @Consumes(MediaType.APPLICATION_JSON)
    @Get("${api_endpoint}")
    String test(String test);

}
```

When i call this API, i receive this error:
22:36:30.433 [default-nioEventLoopGroup-1-3] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Error instantiating bean of type  [io.micronaut.security.authentication.Authenticator]

Message: Bean Factory [Definition: io.micronaut.security.oauth2.endpoint.token.request.password.PasswordGrantFactory] returned null
Path Taken: new SecurityFilter(Collection securityRules,[Collection authenticationFetchers],SecurityConfiguration securityConfiguration) --> new BasicAuthAuthenticationFetcher([Authenticator authenticator],TokenConfiguration configuration) --> new Authenticator([Collection authenticationProviders],SecurityConfiguration securityConfiguration)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.security.authentication.Authenticator]
