### ISSUE TITLE
Should be able to view why authentication has failed for a given JWT

### ISSUE THREAD

**Issue by thomasmillercf** [micronaut-projects/micronaut-security#1216]
### Expected Behavior

When sending an invalid JWT to the service, I should be able to 
   - View logs to see why its invalid
   - The AuthorizationException should contain why it has failed invalid

Basically I should be able to work out why is my application returning 401, so I can tell my consumers of the application what they are doing wrong

### Actual Behaviour

When sending an invalid JWT to the service, I should be able to 
   - View logs to why it failed
   - The AuthorizationException  field `authentication` is null

### Steps To Reproduce

Send a JWT which is expired, missing claim, invalid jwt

    implementation 'io.micronaut.security:micronaut-security-oauth2:3.9.0'
    implementation 'io.micronaut.security:micronaut-security-jwt:3.9.0'

https://micronaut-projects.github.io/micronaut-security/latest/guide/#jwks
```
micronaut:
  security:
    token:
      jwt:
        signatures:
          jwks:
            awscognito: 
              url: 'https://cognito-idp.eu-west-1.amazonaws.com/eu-west-XXXX/.well-known/jwks.json'
```

### Environment Information

Windows 11 WSL Ubuntu 

### Version

3.8.0
