### ISSUE TITLE
Question: Is it possible to configure keycloak for multiple realms?

### ISSUE THREAD

**Issue by lucasmogari** [micronaut-projects/micronaut-security#14]
I'd like to authenticate on multiple realms based on the path or param.

Something like this example: https://github.com/keycloak/keycloak/tree/master/examples/multi-tenant/src/main/java/org/keycloak/example/multitenant

**Comment by jameskleeh** [comment]
With the latest snapshot this is possible by supplying multiple configurations

```
micronaut:
  security:
    oauth2:
      clients:
        realm1:
          client-id: ...
          client-secret: ...
          openid:
            issuer: ...
        realm2:
          client-id: ...
          client-secret: ...
          openid:
            issuer: ...
```
