### ISSUE TITLE
OKta ID Token

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-security#1474]
### Issue description

> Hello, I have a question, mostly asking for advice about best practice. We are trying to understand what's the best approach for managing the following situation. Sorry in advanceif it will be quite long message.
> We have a Micronaut app with some endpoint authorized via bearer token using Okta as provider. it worked until we didn't update from Micronaut 3.9 to Micronaut 3.9.7 (then same issue of course on the last 3.10.2).
> Basically we found that in some minor 3.9.x version Micronaut Security was updated and our old configuration for auth didn't work anymore:

```yaml
authentication: idtoken   
oauth2:
    clients:
        okta:
            openid:
                issuer: ${OIDC_ISSUER_DOMAIN}
```

> as you can see in our previous config we used authentication: idtoken as described here https://guides.micronaut.io/latest/micronaut-oauth2-okta-gradle-kotlin.html

After Micronaut Security it update didn't work anymore and we understood while debugging that it started to require a new configuration for client-id which should match the content of the audience (aud) token claim ( I guess previously there was a bug so it wasn't checked).

As our Okta Authorization Server doesn't return the ClientId in aud claim but the Auth Server url instead, we tried to use the following new configuration:

```
authentication: bearer   
    token:
        jwt:
            signatures:
               jwks:
                   okta:   
                       url: ${OIDC_ISSUER_DOMAIN:
```
