### ISSUE TITLE
Token Propagation and OpenID "azp" claim validation issues

### ISSUE THREAD

**Issue by ArnauAregall** [micronaut-projects/micronaut-security#1543]
### Issue description

Hello, 

I have a use case where two Micronaut services are secured using OpenID (`idtoken`) with an OAuth2 issuer (Keycloak) within the same realm. 

Each service is configured to use it's own realm client.

At application level, one service calls the other using HTTP client interfaces, using JWT Token Propagation feature.

**identity-service**:

```yml
micronaut:
  application:
    name: identity-service
  security:
    intercept-url-map:
      - pattern: /api/**
        access:
          - isAuthenticated()
    authentication: idtoken
    oauth2:
      clients:
        keycloak:
          client-id: '${micronaut.application.name}'
          client-secret: '${OAUTH2_IDENTITY_CLIENT_SECRET}'
          issuer: 'http://localhost:9999/realms/test-realm'
```

**pet-service** (calls `identity-service`):
```yml
micronaut:
  application:
    name: pet-service
  http:
    services:
      identity-service:
        url: "http://identity-service"
  security:
    intercept-url-map:
      - pattern: /api/**
        access:
          - isAuthenticated()
    authentication: idtoken
    oauth2:
      clients:
        keycloak:
          client-id: '${micronaut.application.name}'
          client-secret: '${OAUTH2_PET_CLIENT_SECRET}'
    token:
      propagation:
        enabled: true
        service-id-regex: "identity-service"
```

The OAuth clients have configured scopes so the `aud` claims of the JWT token contains the two `client-id`s.

Example decoded JWT payload:

```json
{
  "exp": 1703581274,
  "iat": 1703580974,
  "auth_time": 1703580974,
  "jti": "98e88f17-683f-4ecc-8e70-b29ed6a604ab",
  "iss": "http://localhost:8082/realms/test-realm",
  "aud": [
    "pet-service",
    "identity-service"
  ],
  "sub": "b40af7e9-392d-40e9-9eb7-55993c9d2a8e",
  "typ": "ID",
  "azp": "pet-service",
  "nonce": "5a647d92-97e0-4bec-ba17-d8a116e93494",
  "session_state": "7c02f73a-e92b-4187-a70a-b49464e1c4fb",
  "at_hash": "5LMA6RsrsdBKtNk21bMfMA",
  "acr": "1",
  "sid": "7c02f73a-e92b-4187-a70a-b49464e1c4fb",
  "email_verified": false,
  "preferred_username": "system_test_user"
}
```

My issue is the Authorized Party claim (`azp`) of the token in this case is the `pet-service`, and when `pet-service` performs  the authenticated HTTP call to `identity-service` endpoints using the Token Propagation feature, `identity-service` runs the `io.micronaut.security.oauth2.client.IdTokenClaimsValidator` and [fails at the `validateAzp`](https://github.com/micronaut-projects/micronaut-security/blob/master/security-oauth2/src/main/java/io/micronaut/security/oauth2/client/IdTokenClaimsValidator.java#L276) step, even though the audiences validation is successful.

I've verified that disabling `openid` claims validation on `identity-service` via configuration is a bypass to the issue.
```yml
micronaut:
  security:
    token:
      jwt:
        claims-validators:
          openid-idtoken: false
```yml

But I have also noticed recent clarifications in regards to `azp` were added to OpenID specs, and if I got it right the `azp` should only be validated when using extensions beyond the scope of the spec.

- https://bitbucket.org/openid/connect/issues/973/
- https://bitbucket.org/openid/connect/pull-requests/340/errata-clarified-that-azp-does-not-occur

As framework core committers, which approach would you recommend to solve this issue? 

Do you believe `IdTokenClaimsValidator#validateAzp` should be revisited after OpenID spec clarifications perhaps? 

Thanks a lot in advance.
Arnau.
