### ISSUE TITLE
Configuring an open id client which may expose a jwks_uri via openid configuration should register a JwksSignature bean

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-security#157]
For such configuration:

```yaml
micronaut:
  security:
    enabled: true
    oauth2:
      enabled: true
      clients:
        okta:
          openid:
            issuer: https://{yourOktaDomain}/oauth2/default
```

if the Open ID Configuration endpoint `https://{yourOktaDomain}/oauth2/default/.well-known/openid-configuration`  exposes a `jwks_uri`. A `JwksSignature` should be configured.
