### ISSUE TITLE
Not able to use micronaut to login to AKHQ

### ISSUE THREAD

**Issue by haraldott** [micronaut-projects/micronaut-security#1886]
### Issue description

Hi all, 

we switched from our cookie-based authentication to idtoken-based authentication in our AKHQ service which is using micronaut. While most of the flow appears to work correctly, we are encountering an issue during the SSO callback. Our application logs show the following warning: 

`openIdToken should be present in user details attributes to use micronaut.security.authentication:idtoken`

Below is the configuration we are currently using:

```
micronaut:
  security:
    authentication: idtoken
    enabled: true
    oauth2:
      enabled: true
      clients:
        sso:
          client-id: #censored#
          client-secret: #censored#
          openid:
            issuer: "#censored#"
            authorization:
              acr-values:
                - "gas:strong"
            configuration-path: ".well-known/openid-configuration"
            scope:
              - "openid"
              - "profile"
              - "email"
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: #censored#
```

We also tried the bearer authentication method where we are getting the following error:

`{ "message":"Page Not Found", "_links":{ "self":{ "href":"/oauth/login/sso", "templated":false } } }`

with the following configuration:

```
  micronaut:
    server:
      netty:
        max-header-size: 100000
    security:
      authentication: bearer
      enabled: true
      oauth2:
        enabled: true
        clients:
          sso:
            client-id: <path:dev/sso/akhq#ClientID>
            client-secret: <path:dev/sso/akhq#ClientSecret>
            openid:
              issuer: "#censored#"
              authorization:
                acr-values:
                  - "gas:strong"
              configuration-path: ".well-known/openid-configuration"
      token:
        jwt:
          signatures:
            secret:
              generator:
                secret: #censored#
```

We are wondering if there are any configurations that we are missing here?
