### ISSUE TITLE
Instance of Authentication is null sometimes in io.micronaut.security.rules.SecuredAnnotationRule#check after Micronaut upgrade from 3.9.0 to 4.7.4

### ISSUE THREAD

**Issue by emmersonbonnat-tw** [micronaut-projects/micronaut-security#1937]
### Expected Behavior

After upgrading from Micronaut 3.9.0 to 4.7.4, When the bearer token is valid (has required roles, not expired), the Authentication parameter in io.micronaut.security.rules.SecuredAnnotationRule#check method should not be null.

```
    @Override
    public Publisher<SecurityRuleResult> check(HttpRequest<?> request, @Nullable Authentication authentication) {
```

### Actual Behaviour

The authentication parameter is null and hence, the request is rejected. Reverting the Micronaut version to 3.9.0 resolves the issue.

### Steps To Reproduce

Couldn't reproduce the issue. The request is rejected randomly. Similar request which earlier pass fails now and vice versa.
The behavior sometimes gets triggered during very high load on the server which also didn't have a consistent behavior.
We used the Openrewrite plugin and followed the steps as in https://micronaut.io/2023/07/14/upgrade-to-micronaut-framework-4-with-openrewrite-and-gradle/ to upgrade from Micronaut 3.9.0 to 4.7.4

### Environment Information

- Operating System: linux/amd64
- JDK: Amazon corretto 17
- Micronaut version: 4.7.4
- Micronaut security version:  4.1.0
- Security configuration:
```
micronaut:
  security:
    enabled: true
    token:
      enabled: true
      bearer:
        enabled: true
      jwt:
        signatures:
          jwks:
            remote-jwks-1:
              url: ${URL_1}
            remote-jwks-2:
              url: ${URL_2}
```

### Version

4.7.4
