### ISSUE TITLE
Simplify the configuration of LoginHandlers and Logout Handlers

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-security#246]
Currently, `AccessRefreshTokenLoginHandler` is enabled by default.

It is confusing how to enable `JwtCookieLoginHandler`.  You had to disable the bearer and enable cookie. 

```yaml
micronaut:
    security:
        token:
            jwt:
                bearer:
                     enabled: false
                cookie:
                     enabled: false
```
