### ISSUE TITLE
Session not saved during calling OAuth callback

### ISSUE THREAD

**Issue by lehotskysamuel** [micronaut-projects/micronaut-security#319]
Hi,
I have a following scenario:

1) user is logged out, clicks on login button (GET /oauth/login/keycloak) and is redirected to keycloak login page
2) user submits his credentials and is redirected back to my service (GET /oauth/callback/keycloak?\<parameters\>)
3) micronaut security valides tokens and jumps into login handler.
    - I'm using `DefaultOpenIdClient`, `DefaultOauthController` and `SessionLoginHandler`.
    - I debuged `SessionLoginHandler` and I can see that new Session is being created.
    - However, the method which stores Session and encodes it to cookie or http header is `HttpSessionFilter.encodeSessionId()`. And this filter is being called before `SessionLoginHandler` - when the Session doesn't exist yet. Therefore, session is not saved, authentication isn't stored with it and user remains logged out.

Should saving oauth authentication data in session be supported? I don't see anything in docs that said otherwise. If so, am I doing something wrong or is this a bug?

This is my configuration:
```
  security:
    enabled: true
    authentication: session
    oauth2:
      enabled: true
      default-provider: keycloak
      clients:
        keycloak:
          client-secret: '<my client secret>'
          client-id: '<my client id>'
          openid:
            issuer: 'https://<keycloak host>/auth/realms/<my realm>'
    redirect:
      prior-to-login: true
      logout: http://localhost:3000/logout
      login-success: http://localhost:3000/successful
```

Note on redirect:
On successful authentication, Keycloak returns 302 Found with location `http://localhost:8080/oauth/callback/keycloak?state=...&session_state=...&code=...`, so my browser is the one calling my service. I think this is correct but in docs the chart looks like the caller should be keycloak (https://micronaut-projects.github.io/micronaut-security/latest/guide/#openid-authorization-code). Could this be the source of my problems?

### Environment Information

- **Operating System**: Windows 10 64bit
- **Micronaut Version:** 2.0.0
- **JDK Version:** adopt-openjdk 14.0.2

Thanks
