### ISSUE TITLE
Micronaut doesn't validate the security settings at launch time 

### ISSUE THREAD

**Issue by gauravphoenix** [micronaut-projects/micronaut-security#359]
Micronaut application start-up should fail if the `application.yml` file has invalid security setting. 

### Steps to Reproduce

Generate a project from https://micronaut.io/launch/ and do not select any features i.e. create a micronaut project with the default feature set. 

Now modify your `application.yml` file to enable security. Something like this- 

```yaml
micronaut:
  application:
    name: foo
  security:
    enabled: true
    intercept-url-map:
      - pattern: /foo/*
        access:
          - isAuthenticated()    
    token:
      jwt:
        enabled: true
        signatures:
          jwks:
            foo:
              url: https://foo
```

### Expected Behaviour
The above configuration is a valid security config. If I send a request to the server with a fake Authorization header with a Bearer token, the server should fail the request because the token is fake.

I reckon the actual issue is that Micronaut is not verifying if the provided settings in the application.yml are valid or not. Given the fast start-up goal, I can see why Micronaut would do that. But when it comes to security, I would love Micronaut to be more strict even if means delaying the start-up by a few microseconds.  

The Micronaut security project documentation https://micronaut-projects.github.io/micronaut-security/latest/guide/ does state that -
>To use the Micronaut’s security capabilities you must have the security dependency on your classpath:

But I think that many users don't read the documentation end to end before using the frameworks. Moreover, even if you read the documentation, it is quite possible to forget to add the dependencies. 

If the project owners feel that failing the launch of Micronaut if the security settings couldn't be applied is quite strict, perhaps, a warning message can be displayed at the start-up. 

### Actual Behaviour

Server does not fail the request because I forgot to add required dependencies like these- 

```
    <dependency>
      <groupId>io.micronaut.security</groupId>
      <artifactId>micronaut-security-jwt</artifactId>
    </dependency>
   
    <dependency>
      <groupId>io.micronaut.security</groupId>
      <artifactId>micronaut-security</artifactId>
    </dependency>
```

### Environment Information

- **Micronaut Version:** `2.0.1`
- **JDK Version:** 11

**Comment by sdelamo** [comment]
If I understand you correctly what you suggesting is that if you forgot to add security dependencies to your build but you have security related configuration in your app, the app should fail. 

I am of the opinion that developers should be responsible to add the necessary dependencies to enable micronaut to understand their configuration. Moreover, in case of security they should have tests to ensure their endpoint are returning 401 by default once security is added. 

Moreover, in micronaut 2.0 the following snipped is no longer necessary. Once you have the dependencies, we enable security by default. 

```yaml
micronaut:
  security:
    enabled: true
    token:
      jwt:
        enabled: true
```

We have been always trying to document that you have add the dependencies. 

For example, we have sections in our guides such as: 

https://guides.micronaut.io/micronaut-security-basicauth/guide/index.html#dependency

Microanut core does not know about the configuration exposed by other modules (e.g. security). Thus, to support what you are requesting we will need to add logic to core to do this kinds of checks. I don’t think that is mantainable. 

Thanks for reporting @gauravphoenix but I am going to close the issue for now.
