### ISSUE TITLE
JWT Rotate Signature Secrets

### ISSUE THREAD

**Issue by JouperCoding** [micronaut-projects/micronaut-security#411]
When creating Access Tokens / Refresh Tokens, there seems to be no way to rotate the secret without breaking all of the already issued JWT tokens for each users.

An example workaround for Refresh Tokens would be to create a custom class which 

@Replaces(SignedRefreshTokenGenerator.class)

And then gets 2 secrets and validates tokens against both secrets and only issues new tokens by a primary signer. (See example below).

Is there a reason why this is not supported? Rolling secrets without breaking old issued tokens to avoid system being down seems like a use case that should be supported by default?

```java
package yggdrasil.api.controllers.authentication;

import com.nimbusds.jose.*;
import com.nimbusds.jose.crypto.MACSigner;
import com.nimbusds.jose.crypto.MACVerifier;
import edu.umd.cs.findbugs.annotations.NonNull;
import io.micronaut.context.annotation.Replaces;
import io.micronaut.context.annotation.Requires;
import io.micronaut.context.exceptions.ConfigurationException;
import io.micronaut.security.authentication.UserDetails;
import io.micronaut.security.token.generator.RefreshTokenGenerator;
import io.micronaut.security.token.jwt.generator.RefreshTokenConfiguration;
import io.micronaut.security.token.jwt.generator.SignedRefreshTokenGenerator;
import io.micronaut.security.token.validator.RefreshTokenValidator;
import net.minidev.json.JSONObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import yggdrasil.api.properties.YggdrasilJwtProperties;

import javax.inject.Singleton;
import java.text.ParseException;
import java.util.Optional;
import java.util.UUID;

import static java.nio.charset.StandardCharsets.UTF_8;


@Singleton
@Replaces(SignedRefreshTokenGenerator.class) // Replaces the entire SignedRefreshTokenGenerator by my custom class below
@Requires(beans = RefreshTokenConfiguration.class)
@Requires(beans = YggdrasilJwtProperties.class) // Injects my custom properties
public class YggdrasilToken implements RefreshTokenGenerator, RefreshTokenValidator {

	private static final Logger logger = LoggerFactory.getLogger(YggdrasilToken.class);

	private final JWSAlgorithm algorithm;

	private final JWSVerifier currentVerifier;
	private final JWSVerifier previousVerifier;
	private final JWSSigner currentSigner;

	public YggdrasilToken(RefreshTokenConfiguration test, YggdrasilJwtProperties config){
		this.algorithm = JWSAlgorithm.HS256;

                // Gets the current secret that should be used when issuing new tokens
		byte[] currentSecret = config.getJwtAccessTokenSecretCurrent().getBytes(UTF_8); 
               // Get the old secret that should be used to validate old tokens during the rollover period
		byte[] previousSecret = config.getJwtAccessTokenSecretPrevious().getBytes(UTF_8); 

		try {
			this.currentSigner = new MACSigner(currentSecret);
		} catch (JOSEException e) {
			throw new ConfigurationException("unable to create a signer", e);
		}
		try {
			this.currentVerifier = new MACVerifier(currentSecret);
			this.previousVerifier = new MACVerifier(previousSecret);
		} catch (JOSEException e) {
			throw new ConfigurationException("unable to create a verifier", e);
		}
	}

	@NonNull
	@Override
	public String createKey(@NonNull UserDetails userDetails) {
		return UUID.randomUUID().toString();
	}

	@NonNull
	@Override
	public Optional<String> generate(@NonNull UserDetails userDetails, @NonNull String token) {
		logger.info(token);
		logger.info(userDetails.getUsername());
		try {
                        // Below line has the following issue https://github.com/micronaut-projects/micronaut-security/issues/410
                        // Should probably follow the RFC 7519 standard and always ensure the Paylod is a JSON object?
			JWSObject jwsObject = new JWSObject(new JWSHeader(algorithm), new Payload(token));

                        // Sign with the currentSigner (in use secret)
			jwsObject.sign(currentSigner);
			return Optional.of(jwsObject.serialize());
		} catch (JOSEException e) {
			if (logger.isWarnEnabled()) {
				logger.warn("JOSEException signing a JWS Object");
			}
		}
		return Optional.empty();
	}

	@NonNull
	@Override
	public Optional<String> validate(@NonNull String refreshToken) {
		JWSObject jwsObject = null;
		try {
			jwsObject = JWSObject.parse(refreshToken);
                        // Validate tokens with both the currentVerifier and previousVerifier (For tokens that where issued during the roll over period)
			if (jwsObject.verify(currentVerifier)) {
				return Optional.of(jwsObject.getPayload().toString());
			}
			if (jwsObject.verify(previousVerifier)){
				return Optional.of(jwsObject.getPayload().toString());
			}
		} catch (ParseException e) {
			if (logger.isWarnEnabled()) {
				logger.warn("Parse exception parsing refresh token {} into JWS Object", refreshToken);
			}
			return Optional.empty();
		} catch (JOSEException e) {
			if (logger.isWarnEnabled()) {
				logger.warn("JOSEException parsing refresh token {} into JWS Object", refreshToken);
			}
		}
		return Optional.empty();
	}
}
```

**Comment by jameskleeh** [comment]
So the issue I think with this in general is that when the app restarts all previous tokens will no longer validate because the previous signature is stored in memory. We can make this api extensible to allow for this sort of custom behavior but I'm not sure we could implement this sort of thing by default. There are a lot of variables that we couldn't make assumptions about

**Comment by JouperCoding** [comment]
@jameskleeh  Yes, im running this in a AWS Lambda function so the secret is only "okay" for the 15 min that context is running. If we change secret at any points all of the tokens given out would start failing. So it would be nice to at least be able to validate issued tokens by the old secrets but as soon we have changed to a new secret all new tokens should be issued with the new secret.

**Comment by JouperCoding** [comment]
Hello @jameskleeh after some more testing I think I was able to get it to work with the following.

I registered two beans of primary & secondary which both has two different secrets. Then I used the primary secret for the secret signature. i.e the token that is returned from /login will always have a signature based on my primary secret.

And any other endpoint will allow both tokens from secret primary & secondary since all beans of SecretSignatureConfiguration is in the JWT validation process.

I will investigate if I find something similar works for JWS (As we want old JWS to work until next /login is issued with a new secret).


```java

package yggdrasil.api.controllers.authentication;

import io.micronaut.context.annotation.Bean;
import io.micronaut.context.annotation.Factory;
import io.micronaut.security.token.jwt.signature.SignatureGeneratorConfiguration;
import io.micronaut.security.token.jwt.signature.secret.SecretSignature;
import io.micronaut.security.token.jwt.signature.secret.SecretSignatureConfiguration;

import javax.inject.Named;

@Factory
public class YggdrasilTest {

	@Bean
	@Named("primary")
	SecretSignatureConfiguration primary(){
		SecretSignatureConfiguration primarySecretSignatureConfiguration = new SecretSignatureConfiguration("JWT-Primary-Secret");
		primarySecretSignatureConfiguration.setSecret("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
		return primarySecretSignatureConfiguration;
	}

	@Bean
	@Named("secondary")
	SecretSignatureConfiguration secondary(){
		SecretSignatureConfiguration secondarySecretSignatureConfiguration = new SecretSignatureConfiguration("JWT-Secondary-Secret");
		secondarySecretSignatureConfiguration.setSecret("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb");
		return secondarySecretSignatureConfiguration;
	}

	@Bean
	@Named("generator")
	SignatureGeneratorConfiguration signatureGeneratorConfiguration(@Named("primary") SecretSignatureConfiguration configuration) {
		return new SecretSignature(configuration);
	}

}

```

**Comment by sdelamo** [comment]
@JouperCoding it is easy to create rotating keys with JWK and Micronaut. 

This is what I typically do: 

I have a CLI application to generate JWK as JSON: 

```java
import com.nimbusds.jose.JOSEException;
import com.nimbusds.jose.JWSAlgorithm;
import com.nimbusds.jose.jwk.KeyUse;
import com.nimbusds.jose.jwk.RSAKey;
import com.nimbusds.jose.jwk.gen.RSAKeyGenerator;
import io.micronaut.configuration.picocli.PicocliRunner;

import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

import java.util.UUID;

@Command(name = "keysgen", description = "Generates a Json Web Key (JWT) with RS256 algorithm.",
        mixinStandardHelpOptions = true)
public class KeysgenCommand implements Runnable {

    @Option(names = {"-kid"}, required = false, description = "Key ID. Parameter is used to match a specific key. If not specified a random Key ID is generated.")
    private String kid;

    public static void main(String[] args) throws Exception {

        PicocliRunner.run(KeysgenCommand.class, args);
    }

    public void run() {

        try {
            RSAKey jwk = new RSAKeyGenerator(2048)
                    .algorithm(JWSAlgorithm.RS256)
                    .keyUse(KeyUse.SIGNATURE) // indicate the intended use of the key
                    .keyID(kid != null ? kid : generateKid()) // give the key a unique ID
                    .generate();

            System.out.println(jwk.toJSONString());

        } catch (JOSEException e) {
            e.printStackTrace();
        }
    }

    private String generateKid() {
        return UUID.randomUUID().toString().replaceAll("-", "");
    }
}
```

I generate two keys and I setup in config: 

```yaml
app:
  primary-jwk: '{"p":"9_FVdg8MLqnLQHqSVmSb-UKDNKuK7Ad-483Kjun9H7vMi2cn6yw8ZlYMkpCrNCMtmtgHxlRGApoWtj9YEpKBoKrwYGEJyH0wAXOwI-lV-s2EPf4WT7wgGShL1iD8SRpaO4p531Ila55lW_cWdnTcMGMgw42LtDyRFlmixthkhds","kty":"RSA","q":"nl_V-SUXYgz_C-bU_wf4uGKnNNQedR9oOrTd5IS1V1witTRmP9jrJNqGo0wkL03PtzpDdOxrlSP2PDCWDzvz2UmOJE8fAvP2WBoyBvrKT3iZzzQb3jgXRVq0jqyMPoO673N2IYpgPs20-yMVC0FbuaxOzYh2QdnrJF5lJ2yXtg0","d":"QedpxKPa9I7P01C8mNZKlrzVd-aFbbUlIP3qFFr5r8egK3nMaZ0q4AWY1wDsS8QGGTgXE3aeiPJLf6B7cBZWoWuSODlkQEjwIi05TvUCoxP0ixAqQRpBk-m3MhuSyi7XYykXhooZXClsIPwaW2djE05QY9n-kdHMMcNFwmdmCMo4yZBVP_gBooCva9suJfbVCMzImoA9UdqrPR6QHwh9Ze-CrKW8GCE45XAPeEiGwkwtx5tjbkakNZ8XMLnQv5AUnoO8SlU3oNGkhdJPzA9Ysh6_wgAvJgvc6vywNA0frVrr0wWm6kGogzWzkkgV6moSQsRGWeEY2qi3TSv2x_iLkQ","e":"AQAB","use":"sig","kid":"a5c3a36d3edf4317ba328d7832b9bde5","qi":"FGB5jdA4KuI1vRsTSJYtBy0QmxB89DBEregYEsCwYlZycoALb5n9OHS5r4SC4NyJ6Gtm6UC7Mb11EB6z5hfLOru3KW93rlhGKagyGMN2D-MG8pYPRh3KApO6-K48W_wmCeaRvdP3lXvAQSLwYlbLo8OROSwbFLAd1PLHI5ILSjY","dp":"MWuqNDEFpZt0hvKnjo7ZRBLM4ke7FhbcZP3U_S2IpbWiLLswCsEzfNZ0BRbO-UJ1yaJ70j1kAwrBsivoGzOWoPbRmPRepdbGJdPwbQgKekZSsKSfv97oqvsMOq8yekPFbo7Iggn2qX_WBkG2-X-LkB2CH1hsW02jQcg2GNpzFvc","alg":"RS256","dq":"Dl-sT9xp7uA3FaFxm2Ph0vpBKq5FxWOAVjOsH91bh_44uDF1Rj4tuT6MEa4Laq-pNnv3O1lpujN1WakfNWq_iuz-FZWIvv_dT8mw2KlSSzwq2X9lOBnnIshEst4-LD5QbQMRqaGhcpHA5zob4tWfuY5F6KmF8hwRF0_p5lYYvtE","n":"mWPEiq3c-6uY9R0JoheiAK-KpyOYr4bagfbTx_ggiVSto_mZOUXh06yC0JOICLsVtCjzd8BN9xkKzNB6oc84o2CH5hE97cFFpsUHCduvRI5C3ll5DnXQhoMg5EJzAYYmrOz8mK4e2-6L_tagoAb37tkH5Jn_ICIFTjNhkU_PRWCJGJNprcJM2_pDxECj27mUDtN5JdhBAUzPHvn1eW5DqEfF9siiLD3vuuu76Vs-hNqgv3GuE3Rt3nud5vvySdIVqZVBKBvdvAoWWDbqYX2q0kSLSNoFIo5ZBzUUv9XXhLkCK5vVSznisE9HQ7vBTXvMSLMEn3LikzxVZHkQzHF-Hw"}'
  secondary-jwk: '{"p":"_JAVBBp9XGFqStYoi369klYUbIRafcnwLltqqEGH7qK5xSAMw5Ug6Kldygja3VMiJsgILzoyM9zJyoqDjrd-aR75kufhn40lIWVhPf4TWomdx0gnAcxIBFVlKvgN3-NuGOCOsolPRm_z3--ChTU7yY0cXFuUrqSR3KZcfS356uc","kty":"RSA","q":"wnVRtLnlbc1-NZAQscYDNRYYiDdIq7tpZ6Vj_X_z5UCYt_nAZZJtEtAanPBQWgE2FfA1F76T4iFhHNBm03WlpFJDH6N44olUbOodvvEQeUE83jGACCRdj-ia8X_DztoKqTNQ2Ai55eiTkxUABzraAZBU8boFyWfQ25FQVGYbe-M","d":"mgAJXB2CBYYze2xp-MYXFLmIL1tBZFJ_DExM1BNqaXFosZ4sEyb670Jk5sHRJX3rPXY7KjevsN1E6jd98-nk1Rtc6MHFQdxu9NPiJdQtmjKf2aCVAgMsNZwBdq1dhjaIgE9cssK9l2XNXPHVrp3xhIuOXtZ2ceWgHSEbKZAwj2IxziQVjeUVfAGByfc_S76LfmaBpErQulcAKFa_qx30Ea4r4xodXpeEOs4vaPmAxeaJo4IRX6bnr9163lch07NzCK-sS83Lx25HlfpK-KKqrl99oSEa4S7Qr7aUIjO-LM1O9al82w-efYmNxkxZKH2fXdjw9bnqd7hPVC8B5SYiAQ","e":"AQAB","use":"sig","kid":"41ccf091ecc04df88a402e4cd1705acd","qi":"2TWsyw1tYbimP5J5WtF1H-1xBb8IJBejIbw9cdGLEK2XIvV3wrSlwdFD-B7ce87__CB3QMmj2sukB8Kfw5CWaouE3V-1QfrB_PHqpizR0YC2emazhSMOLB9wtrA_Kv0Qa0IT6derBUuvMa-kRzmQNoyADkDShWDaiT1UJmyCjFQ","dp":"QuWrG2Yk1GZdMCtfm-tbLTqtuDyqd20YuD6wlpac-cGScTtXBisnB1ltJUmJJ1yQzDLpsBC7IW-W55Ye2JuT2SZCNv5Cje9l6V2gDzqQR8fxyco7wscoQDWaUXJYwnfMPrykL3gdTmvy7drT-JKsHmvJGlGLpWKj3A0YrHOUIfs","alg":"RS256","dq":"l45kXdy8ybVs9kYQHN3dRhSwjgm4Y9AvOI6YvcxpxHVyEYFfyEo1JIJ5G3PYzC1BgBu05YqtK4Mkcxah7ZE1xjovAouf_b9Ww4Q8JsMvObH0xKADz1S4bx61FB-l9qPNx02tZpJ2gI-h5PJrETd3Ddz1t2hqdiyphVdeKklihk0","n":"v9juYppOpvguGbFjh2Wa6fgLGWYTnk5Xqcme_Vqe0RvOVzxAZU8sVQJHNSHoNfOfvnMx_NJYVWV6bjsOiYl2pu4uHM0mA0c-rrqpY-x5X8R8okKQDTKtbzjzArgoHV9e8XqJCr3mRy31vGoianNjNE6S5HYjO57rdWrI7YZbF8RmL40zx0eOPLknErmYiKKuzeXy6rmIOO4dKbd8CFLetWV5cpb5KG9R1M9_iKDUmfxwd4SKt6Vrv5gdNpCw3dQL3ckZ6z83clHD5e21PYhICm-6CHCEqCEmdDm-2La-yB3MXpS7LTEBboZCMwp8z86DTpyqpvDkq2MQudjWqNVH1Q"}'
```

NOTE: Don't commit those private keys in application configuration but in env. variables or other external configuration. 

I create a config file to read them: 

```java
package com.example;

import edu.umd.cs.findbugs.annotations.NonNull;
import io.micronaut.context.annotation.ConfigurationProperties;

import javax.validation.constraints.NotBlank;

@ConfigurationProperties("app")
public class AppConfiguration {
    @NonNull
    @NotBlank
    private String primaryJwk;

    private String secondaryJwk;

    @NonNull
    String getPrimaryJwk() {
        return primaryJwk;
    }

    void setPrimaryJwk(@NonNull String primaryJwk) {
        this.primaryJwk = primaryJwk;
    }

    @NonNull
    String getSecondaryJwk() {
        return secondaryJwk;
    }

    void setSecondaryJwk(@NonNull String secondaryJwk) {
        this.secondaryJwk = secondaryJwk;
    }
}
```

Then I have a signature configuration to sign tokens, the one annoated with `@Named("generator")`and the secondary key is only used for validation: 

```java
package com.example;

import com.nimbusds.jose.Algorithm;
import com.nimbusds.jose.JOSEException;
import com.nimbusds.jose.JWSAlgorithm;
import com.nimbusds.jose.jwk.JWK;
import com.nimbusds.jose.jwk.RSAKey;
import io.micronaut.context.exceptions.ConfigurationException;
import io.micronaut.security.token.jwt.endpoints.JwkProvider;
import io.micronaut.security.token.jwt.signature.rsa.RSASignatureGeneratorConfiguration;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.security.interfaces.RSAPrivateKey;
import java.security.interfaces.RSAPublicKey;
import java.text.ParseException;
import java.util.Collections;
import java.util.List;

public abstract class AbstractRSASignatureConfiguration implements RSASignatureGeneratorConfiguration, JwkProvider {
    private static final Logger LOG = LoggerFactory.getLogger(AbstractRSASignatureConfiguration.class);

    private final RSAKey rsaKey;

    public AbstractRSASignatureConfiguration(String jwkString) {
        try {
            JWK jwk = JWK.parse(jwkString);
            if (!(jwk instanceof RSAKey)) {
                if (LOG.isErrorEnabled()) {
                    LOG.error("JWK is not an RSAKey");
                }
                throw new ConfigurationException("JWK is not an RSAKey");
            }
            this.rsaKey = (RSAKey) jwk;
        } catch (ParseException e) {
            if (LOG.isErrorEnabled()) {
                LOG.error("Could not parse JWK JSON string {}", jwkString);
            }
            throw new ConfigurationException("could not parse JWK JSON String");
        }
    }

    @Override
    public RSAPrivateKey getPrivateKey() {
        try {
            return rsaKey.toRSAPrivateKey();
        } catch (JOSEException e) {
            if (LOG.isErrorEnabled()) {
                LOG.error("Could not get rsa private key {}", e.getMessage());
            }
            return null;
        }
    }

    @Override
    public JWSAlgorithm getJwsAlgorithm() {
        Algorithm algorithm = rsaKey.getAlgorithm();
        if (algorithm instanceof JWSAlgorithm) {
            return (JWSAlgorithm) algorithm;
        }
        if (algorithm != null) {
            return JWSAlgorithm.parse(algorithm.getName());
        }

        if (LOG.isErrorEnabled()) {
            LOG.error("algorithm is not a JWSAlgorithm");
        }
        return null;
    }

    @Override
    public RSAPublicKey getPublicKey() {
        try {
            return rsaKey.toRSAPublicKey();
        } catch (JOSEException e) {
            if (LOG.isErrorEnabled()) {
                LOG.error("Could not get rsa public key {}", e.getMessage());
            }
            return null;
        }
    }

    @Override
    public List<JWK> retrieveJsonWebKeys() {
        return Collections.singletonList(rsaKey.toPublicJWK());
    }
}
```

```java
package com.example;

import javax.inject.Named;
import javax.inject.Singleton;

@Named("generator")
@Singleton
public class PrimaryRSASignatureConfiguration extends AbstractRSASignatureConfiguration {
    public PrimaryRSASignatureConfiguration(AppConfiguration appConfiguration) {
        super(appConfiguration.getPrimaryJwk());
    }
}
```

```java
package com.example;

import javax.inject.Singleton;

@Singleton
public class SecondaryRSASignatureConfiguration extends AbstractRSASignatureConfiguration {
    public SecondaryRSASignatureConfiguration(AppConfiguration appConfiguration) {
        super(appConfiguration.getSecondaryJwk());
    }
}
```

With the above configuration, the public JWK are exposed in the `/keys` endpoint. 

When it is time to rotate the keys, you generate a new JWK. You move the primary to secondary and add the new key to primary. You will be able to validate JWT issued before the rotation because the old primary key is now secondary and thus it is used for validation.
