### ISSUE TITLE
OpenId Validation Features without OAuth login handler(s)

### ISSUE THREAD

**Issue by h4t0n** [micronaut-projects/micronaut-security#439]
I use Micronaut to validate a Google OpenID JWTs without needing the oauth login handler. I know that I can use jwks url with bearer token validation configuration. But for google the standard endpoint is the openid configuration, indeed jwks uri may change.

Is it possibile to use openid configuration only for token validation?

**Comment by sdelamo** [comment]
I think we should support this. 

how do you envision this to work @h4t0n ?

We could support: 

```
micronaut:
  security:
    token:
      jwt:
        signatures:
          jwks:
            google:
              url: 'https://accounts.google.com/'
              type: 'openid-configuration'
```

and if you specify a type of openid-configuration we search for the jwks_uri exposed in the well-known/openid-configuration

or did you just want to have something like this: 

```
micronaut:
  security:
    oauth2:
      clients:
        google: 
          client-id: '${OAUTH_CLIENT_ID}'  
          client-secret: '${OAUTH_CLIENT_SECRET}' 
          openid:
            issuer: 'https://accounts.google.com' 
```

We probably need to add a claims validator to ensure we only accept tokens addressed to an OAuth 2.0 client.

**Comment by h4t0n** [comment]
What about something like that?
```
micronaut:
  security:
    oauth2:
      clients:
        google: 
          type: 'verify'
          client-id: '${OAUTH_CLIENT_ID}' 
          openid:
            issuer: 'https://accounts.google.com'
```

Because here we can use the client-id to validate only its tokens. And do we need the client-secret? I think it can be omitted to verify the token.

**Comment by sdelamo** [comment]
I agree with you, `client_secret` should not be necessary. 

Probably, we should not require `type: verify` either.

**Comment by h4t0n** [comment]
The type 'verify' or something similar should be used to disable OAuth login endpoints probably. So it is clear that the OAuth2 configuration is only used to verify tokens.

**Comment by sdelamo** [comment]
@h4t0n using authentication mode `idtoken` should be what you need. We already have a factory which registers the JWKS uri obtained through discovery: 

[JwksUriSignatureFactory](https://github.com/micronaut-projects/micronaut-security/blob/master/security-oauth2/src/main/java/io/micronaut/security/oauth2/client/JwksUriSignatureFactory.java)

I've created a [PR](https://github.com/micronaut-projects/micronaut-security/pull/456) which includes  a claims validator to validate that the `aud` claim contains the `client_id`, that the `iss`  matches and for multiple audiences the `azp`. 

So, you will just need: 

```yaml
micronaut:
  security:
    authentication: idtoken
    oauth2:
      clients:
        google: 
          client-id: '${OAUTH_CLIENT_ID}' 
          openid:
            issuer: 'https://accounts.google.com'
```
