### ISSUE TITLE
GraalVM and Micronaut Security LDAP not working

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-security#591]
## Step to reproduce

Create an app: 

JDK: 11
Micronaut Version: 2.4.0
Language: Java
Test Framework: Spock
Features: 
`security-jwt`
`security-ldap`

dependencies: 
```
    implementation("io.micronaut.security:micronaut-security-jwt")
    implementation("io.micronaut.security:micronaut-security-ldap")
```

Configuration: 

```yaml
---
micronaut:
  security:
    authentication: bearer
    ldap:
      default:
        context:
          server: 'ldap://ldap.forumsys.com:389'
          managerDn: 'cn=read-only-admin,dc=example,dc=com'
          managerPassword: 'password'
        search:
          base: "dc=example,dc=com"
        groups:
          enabled: true
          base: "dc=example,dc=com"

```

Create a POJO annotated with `@Introspected`

```java
package com.example;

import io.micronaut.core.annotation.Introspected;

@Introspected
public class Foo {
}
```

Without a micronaut bean or a `@Introspected` class `META-INF/native-image/com.example/demo/reflect-config.json` is not created.

Use GraalVM:  21.0.0.2.r11-grl

```bash
% sdk use java  21.0.0.2.r11-grl
% gu install native-image
% ./gradlew nativeImage
% ./build/native-image/application
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v2.4.0)

12:31:51.174 [main] DEBUG i.m.s.a.AuthenticationModeCondition - CookieBasedAuthenticationModeCondition} is not fulfilled because micronaut.security.authentication is not set.
12:31:51.182 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 22ms. Server Running: http://localhost:8080
````

## Expected

```bash
 % curl -ivX POST -H "Content-Type: application/json" -d '{"username": "euler", "password": "password"}' localhost:8080/login

HTTP/1.1 200 OK

{"username":"euler","roles":["Mathematicians"],"access_token":"eyJhbGciOiJub25lIn0.eyJzdWIiOiJldWxlciIsIm5iZiI6MTYxNTU0ODg0OCwicm9sZXMiOlsiTWF0aGVtYXRpY2lhbnMiXSwiaXNzIjoiZGVtbyIsImV4cCI6MTYxNTU1MjQ0OCwiaWF0IjoxNjE1NTQ4ODQ4fQ.","token_type":"Bearer","expires_in":3600}
```

## Current Behaviour

```bash
 % curl -ivX POST -H "Content-Type: application/json" -d '{"username": "euler", "password": "password"}' localhost:8080/login

HTTP/1.1 401 Unauthorized

* Connection #0 to host localhost left intact
{"message":"Unknown","_links":{"self":{"href":"/login","templated":false}}}* Closing connection 0
```
