### ISSUE TITLE
Slack OAuth

### ISSUE THREAD

**Issue by brunodomenici** [micronaut-projects/micronaut-security#603]
Hi,

I'm trying to configure Slack's OAuth provider in my application, but in this provider, we have a parameter (out of OAuth Spec in my opinion) which is the `user_scope` in addition of `scopes` and we can't configure it in oauth config section. 
Without this config, the redirect url generated to Slack misses the parameter `user_scope`. 

Example:

```yaml
    oauth2:
      enabled: true
      default-provider: slack
      clients:
        slack:
          client-id: 'xxx'
          client-secret: 'xxx'
          scopes:
            - identity.email
          user_scope:
            - identity.email
          authorization:
            url: https://slack.com/oauth/v2/authorize
          token:
            url: https://slack.com/api/oauth.v2.access
            auth-method: client-secret-post
```

Slack OAuth doc: https://api.slack.com/authentication/oauth-v2#asking

Any one have facing the same problem with this kind of OAuth provider?

Thank you
