### ISSUE TITLE
Java example for OpenID config

### ISSUE THREAD

**Issue by vdobrikov** [micronaut-projects/micronaut-security#7]
Please add Java example how to add OpenID config. I saw there is a Groovy one, but unfortunately I'm not that familiar with it. I think the same for many others.

**Comment by jameskleeh** [comment]
The oauth2 config for the above would now be:
```
micronaut:
  security:
    enabled: true
    oauth2:
      clients:
        keycloak:
          client-id: '****'
          client-secret: '****'
          openid:
            issuer: https://keycloak.server/auth/realms/master
```
