### ISSUE TITLE
Allow the LDAP group search filter argument to be configured

### ISSUE THREAD

**Issue by yertym** [micronaut-projects/micronaut-security#720]
The LDAP group search is hardcoded to only use the DN of the user as a filter argument. This causes non-standard LDAP setups to fail.

### Steps to Reproduce
```yaml
micronaut:
  security:
    enabled: true
    ldap:
      default:
        enabled: true
        context:
          server: 'ldaps://ldap.example.com:636'
          managerDn: ''
          managerPassword: ''
        search:
          base: "ou=people,dc=example,dc=com"
          attributes:
            - "uid"
        groups:
          enabled: true
          base: "ou=Groups,dc=example,dc=com"
          filter: "(memberUid={0})"
```
User
```
distinguishedName: CN=Test User,OU=People,DC=example,DC=com
uid: tuser
```
Group
```
cn: testGroup
memberUid: tuser
```
Using the configuration above it works correctly when authenticating the user but when searching for groups that the user is in returns no results because memberUid doesn't use the DN of the user but rather username/uid

### Expected Behaviour

The group configuration should allow something apart from the DN to be used as the argument to the filter. The two obvious choices are the DN and the username

### Actual Behaviour
It is hardcoded to use the DN of the user 
https://github.com/micronaut-projects/micronaut-security/blob/1f6e873e4073142f426cf914dd89d4c5185577ff/security-ldap/src/main/java/io/micronaut/configuration/security/ldap/LdapAuthenticationProvider.java#L148

**Comment by jameskleeh** [comment]
Now possible with:

```
micronaut:
  security:
    ldap:
      default:
        groups:
          filter-attribute: uid
```
