### ISSUE TITLE
Regression in native image support for OpenID Connect

### ISSUE THREAD

**Issue by morki** [micronaut-projects/micronaut-security#788]
### Expected Behavior

The native image build of Micronaut application with OpenID Connect features works out of the box in build time and run time.  

The problem is probably with change in Micronaut 3.x where `@Introspected` beans are no longer added automatically to `reflect-config.json`. 

As a workaround, it can be solved with adding this to `reflect-config.json` as generated with native agent:

```json
[
  {
    "name": "io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata",
    "allDeclaredFields": true,
    "allDeclaredMethods": true,
    "allDeclaredConstructors": true
  },
  {
    "name": "io.micronaut.security.oauth2.endpoint.authorization.state.DefaultState",
    "allDeclaredFields": true,
    "allDeclaredMethods": true,
    "allDeclaredConstructors": true
  },
  {
    "name": "io.micronaut.security.oauth2.endpoint.token.response.OpenIdTokenResponse",
    "allDeclaredFields": true,
    "allDeclaredMethods": true,
    "allDeclaredConstructors": true
  },
  {
    "name": "io.micronaut.security.oauth2.endpoint.token.response.TokenResponse",
    "allDeclaredFields": true,
    "allDeclaredMethods": true
  }
]
``` 

### Actual Behaviour

It does work in build time, but throws in run time.

### Steps To Reproduce

Try build native image with application with usage of OpenID Connect configured. Example:

```yml
micronaut:
  security:
    authentication: session
    oauth2:
      clients:
        xxx:
          client-id: yyy
          client-secret: zzz
          openid:
            issuer: https://xxx.yyy/zzz
```

### Environment Information

GraalVM Community 21.2 - Java 11

### Version

3.0.2
