### ISSUE TITLE
interceptUrlMap is ignoring context path

### ISSUE THREAD

**Issue by dlangerenken** [micronaut-projects/micronaut-security#825]
### Expected Behavior

The interceptUrlMap will consider the context-path, such that the following config allows me to access /home/app/anything:
```
micronaut:
  server:
    context-path: /home
  router:
    static-resources:
      default:
        enabled: true
        paths: classpath:static
        mapping: /**
  security:
    interceptUrlMap:
      - pattern: /app/**/*.*
        access: isAnonymous()
```

### Actual Behaviour

I need to add the context-path as part of my pattern for each interceptUrlMap entry:
```
micronaut:
  server:
    context-path: /home
  router:
    static-resources:
      default:
        enabled: true
        paths: classpath:static
        mapping: /**
  security:
    interceptUrlMap:
      - pattern: ${micronaut.server.context-path}/app/**/*.*
        access: isAnonymous()
```

`/home/app/anything` is not accessible otherwise.

### Steps To Reproduce

Use the following application.yml
```
micronaut:
  server:
    context-path: /home
  router:
    static-resources:
      default:
        enabled: true
        paths: classpath:static
        mapping: /**
  security:
    interceptUrlMap:
      - pattern: /app/**/*.*
        access: isAnonymous()
```
Try to access anything under /home/app. 
Change the pattern to `pattern: ${micronaut.server.context-path}/app/**/*.*`. It will now work.

### Version

3.0.1

**Comment by sdelamo** [comment]
I am not sure what to think. I don't think we should change behaviour because it could be consider a breaking changing. Thus, it may break already existing applications.

A current user may have: 

```
micronaut:
  server:
    context-path: /home
  security:
    intercept-url-map:
      - pattern: /home/foo/**
        access: isAnonymous()
```

and we we change it, then intercept-url-map pattern maybe considered `/home/home/foo/**` and thus break their application. 

I think we could add a boolean configuration property such as `micronaut.security.intercept-url-map-patterns-preffixed-with-server-context-path` which defaults to false and if it is changed to true then it behaves as you describe.  

What do you think?
