### ISSUE TITLE
More than 1 route matched: POST - /login, POST - /login

### ISSUE THREAD

**Issue by volgin** [micronaut-projects/micronaut-security#860]
### Expected Behavior

I am following the guide for JWT security:
https://guides.micronaut.io/latest/micronaut-security-jwt-maven-java.html

I added suggested classes and tests to my project. All tests pass. However, when I deploy the app to Google App Engine, I get the following error:

'''More than 1 route matched the incoming request. The following routes matched /login: POST - /login, POST - /login'''

I don't have any controllers with /login endpoint, and all other controllers work normally, without any errors. I am not sure where to look next because I did not provide any custom implementations for LoginController. I only added the following classes from the guide:

AuthenticationProviderUserPassword.java
CustomRefreshTokenPersistence.java
RefreshTokenEntity.java
RefreshTokenRepository.java

I suspect that something funny happens during the deployment process since all the local tests pass. I am using Maven.

### Version

3.1.3

**Comment by graemerocher** [comment]
sounds like the shaded JAR contains duplicate classes

**Comment by volgin** [comment]
All the controllers that I explicitly defined are working correctly. So it's limited to Micronaut security.

I have the following dependencies:

micronaut-security-jwt
micronaut-inject
micronaut-validation
micronaut-http-client
micronaut-http-server-netty
micronaut-runtime
micronaut-data-jdbc
micronaut-jdbc-hikari
micronaut-reactor
micronaut-reactor-http-client
micronaut-gcp-logging
javax.annotation-api

in addition to lombok, postgres, and some Google Cloud libraries. I also have

            <path>
              <groupId>io.micronaut.security</groupId>
              <artifactId>micronaut-security-annotations</artifactId>
              <version>${micronaut.security.version}</version>
            </path>

in annotationProcessorPaths.

**Comment by volgin** [comment]
When I deploy the example app from the guide to the App Engine, I get the same error. The only difference is that I have to add appengine-maven-plugin in order to deploy to the App Engine.

**Comment by SolomanDavis** [comment]
Is there any update on this error? I am getting this error specifically when trying to configure a dex oauth provider. This is my config:

```yaml
  security:
    authentication: session

    reject-not-found: false
    redirect:
      unauthorized:
        url: /oauth/login/dex

    oauth2:
      login-uri: /oauth/login/dex
      callback-uri: /oauth/callback/dex
      default-provider: dex

      clients:
        dex:
          enabled: true
          client-id: <<client-id>>
          client-secret: <<client-secret>>
          authorization:
            url: <<auth-url>>
          token:
            url: <<token-url>>
            auth-method: client-secret-post
```

With this config I'm getting the following error:
```
More than 1 route matched the incoming request. The following routes matched /oauth/login/dex: GET - /oauth/login/dex, GET - /oauth/login/dex
```
